In [3]:
import json
import pandas as pd
import polars as pl

In [4]:
with open("collected_data/session_1755219722_3625_20250815_133117.json",'r') as file:
    test = json.load(file)

In [4]:
test['states'][2]

{'jokers': [],
 'shop': [],
 'deck': [],
 'state_name': 'DRAW_TO_HAND',
 'num_hands_played': 0,
 'blind_id': '1754944416_5440_B1-1_1754944420',
 'timestamp': 1754944420,
 'dollars': 4,
 'consumables': [],
 'round': 1,
 'discount_percent': 0,
 'max_jokers': 0,
 'recent_actions': [{'game_state': 'BLIND_SELECT',
   'context_id': '1754944416_5440_B1-0_1754944419',
   'params': [],
   'blind_id': '1754944416_5440_B1-0_1754944419',
   'timestamp': 1754944419,
   'session_id': '1754944416_5440',
   'action': 'SELECT_BLIND',
   'game_time': 4,
   'context_type': 'blind_session'}],
 'current_round': {'discards_left': 4},
 'tags': [],
 'chips': 0,
 'pack': [],
 'context_id': '1754944416_5440_B1-1_1754944420',
 'game_time': 4,
 'state': 3,
 'hand': [],
 'inflation': 0,
 'deckback': [],
 'session_id': '1754944416_5440',
 'handscores': {'goal': 300, 'score': 0},
 'ante': {'blinds': {'blind_id': '1754944416_5440_B1-1_1754944420',
   'ondeck': 'Small',
   'current': {'chips': 300, 'name': 'Small Blind', 'mult': 1}}},
 'interest_cap': 25,
 'current_state': 3,
 'bankrupt_at': 0,
 'context_type': 'blind_session',
 'received_timestamp': 1754944420.5384574,
 'type': 'game_state'}

In [12]:
pl.from_dicts(test['actions'], strict=False)

SchemaError: failed to determine supertype of list[null] and struct[6]

In [8]:
states = pd.DataFrame(test['states'])
actions = pd.DataFrame(test['actions'])

In [13]:
states.sort_values("timestamp")

,jokers,hand_levels,deck,num_hands_played,timestamp,deckback,consumables,state_name,discount_percent,chips,...,current_state,bankrupt_at,pack,received_timestamp,type,blind_id,context_id,context_type,round_id,shop_id
0,[],"{'Flush House': {'level': 1, 'played': 0, 'vis...",[],12,1755219723,[],[],UNKNOWN,0,211,...,-1,0,[],1.755220e+09,game_state,NaN,NaN,NaN,NaN,NaN
1,[],"{'Flush House': {'level': 1, 'played': 0, 'vis...",[],0,1755219723,[],[],BLIND_SELECT,0,0,...,7,0,[],1.755220e+09,game_state,1755219722_3625_B1-0_1755219723,1755219722_3625_B1-0_1755219723,blind_session,NaN,NaN
2,[],"{'Flush House': {'level': 1, 'played': 0, 'vis...",[],0,1755219727,[],[],DRAW_TO_HAND,0,0,...,3,0,[],1.755220e+09,game_state,1755219722_3625_B1-1_1755219727,1755219722_3625_B1-1_1755219727,blind_session,NaN,NaN
3,[],"{'Flush House': {'level': 1, 'played': 0, 'vis...",[],0,1755219728,[],[],SELECTING_HAND,0,0,...,1,0,[],1.755220e+09,game_state,1755219722_3625_B1-1_1755219727,1755219722_3625_B1-1_1755219727,blind_session,NaN,NaN
4,[],"{'Flush House': {'level': 1, 'played': 0, 'vis...",[],0,1755219733,[],[],HAND_PLAYED,0,0,...,2,0,[],1.755220e+09,game_state,1755219722_3625_B1-1_1755219727,1755219722_3625_B1-1_1755219727,blind_session,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
416,"[{'label': 'Blue Joker'}, {'label': 'Blueprint...","{'Flush House': {'level': 1, 'played': 0, 'vis...",[],58,1755221454,[],[],HAND_PLAYED,0,128649,...,2,0,[],1.755221e+09,game_state,1755219722_3625_B9-27_1755221415,1755219722_3625_B9-27_1755221415,blind_session,1755219722_3625_R9-26_1755221387,NaN
417,"[{'label': 'Blue Joker'}, {'label': 'Blueprint...","{'Flush House': {'level': 1, 'played': 0, 'vis...",[],59,1755221457,[],[],NEW_ROUND,0,133255,...,19,0,[],1.755221e+09,game_state,NaN,NaN,NaN,1755219722_3625_R9-27_1755221457,NaN
418,"[{'label': 'Blue Joker'}, {'label': 'Blueprint...","{'Flush House': {'level': 1, 'played': 0, 'vis...",[],59,1755221457,[],[],GAME_OVER,0,133255,...,4,0,[],1.755221e+09,game_state,NaN,NaN,NaN,1755219722_3625_R9-27_1755221457,NaN
419,[],"{'Flush House': {'level': 1, 'played': 0, 'vis...",[],59,1755221462,[],[],UNKNOWN,0,133255,...,-1,0,[],1.755221e+09,game_state,NaN,NaN,NaN,1755219722_3625_R9-27_1755221457,NaN
420,[],"{'Flush House': {'level': 1, 'played': 0, 'vis...",[],0,1755221462,[],[],MENU,0,0,...,11,0,[],1.755221e+09,game_state,NaN,NaN,NaN,1755219722_3625_R9-27_1755221457,NaN

In [14]:
actions

,game_state,context_id,game_time,blind_id,timestamp,card_info,session_id,action,params,context_type,type,received_timestamp,shop_id,round_id
0,BLIND_SELECT,1755219722_3625_B1-0_1755219727,5,1755219722_3625_B1-0_1755219727,1755219727,[],1755219722_3625,SELECT_BLIND,[],blind_session,player_action,1.755220e+09,NaN,NaN
1,HAND_PLAYED,1755219722_3625_B1-1_1755219727,11,1755219722_3625_B1-1_1755219727,1755219733,"{'hand_played': {'level': 1, 'total_score': 16...",1755219722_3625,PLAY_HAND,"[3, 4, 5, 7, 8]",blind_session,player_action,1.755220e+09,NaN,NaN
2,BUFFOON_PACK,1755219722_3625_S1-1_1755219758,36,NaN,1755219758,"{'set': 'Booster', 'key': 'p_buffoon_normal_2'...",1755219722_3625,USE_BOOSTER_PACK,[],shop_session,player_action,1.755220e+09,1755219722_3625_S1-1_1755219758,1755219722_3625_R1-1_1755219737
3,BUFFOON_PACK,1755219722_3625_S1-1_1755219758,47,NaN,1755219769,"{'set': 'Joker', 'key': 'j_blue_joker', 'name'...",1755219722_3625,ADD_JOKER,[],shop_session,player_action,1.755220e+09,1755219722_3625_S1-1_1755219758,1755219722_3625_R1-1_1755219737
4,SPECTRAL_PACK,1755219722_3625_S1-1_1755219772,50,NaN,1755219772,"{'set': 'Booster', 'key': 'p_spectral_jumbo_1'...",1755219722_3625,USE_BOOSTER_PACK,[],shop_session,player_action,1.755220e+09,1755219722_3625_S1-1_1755219772,1755219722_3625_R1-1_1755219737
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,BLIND_SELECT,1755219722_3625_B9-26_1755221414,1692,1755219722_3625_B9-26_1755221414,1755221414,[],1755219722_3625,SELECT_BLIND,[],blind_session,player_action,1.755221e+09,NaN,1755219722_3625_R9-26_1755221387
254,HAND_PLAYED,1755219722_3625_B9-27_1755221415,1699,1755219722_3625_B9-27_1755221415,1755221421,"{'hand_played': {'level': 6, 'total_score': 33...",1755219722_3625,PLAY_HAND,[1],blind_session,player_action,1.755221e+09,NaN,1755219722_3625_R9-26_1755221387
255,HAND_PLAYED,1755219722_3625_B9-27_1755221415,1707,1755219722_3625_B9-27_1755221415,1755221429,"{'hand_played': {'level': 2, 'total_score': 39...",1755219722_3625,PLAY_HAND,"[1, 2, 3, 8, 9]",blind_session,player_action,1.755221e+09,NaN,1755219722_3625_R9-26_1755221387
256,HAND_PLAYED,1755219722_3625_B9-27_1755221415,1719,1755219722_3625_B9-27_1755221415,1755221441,"{'hand_played': {'level': 6, 'total_score': 33...",1755219722_3625,PLAY_HAND,[2],blind_session,player_action,1.755221e+09,NaN,1755219722_3625_R9-26_1755221387
257,HAND_PLAYED,1755219722_3625_B9-27_1755221415,1733,1755219722_3625_B9-27_1755221415,1755221455,"{'hand_played': {'level': 1, 'total_score': 20...",1755219722_3625,PLAY_HAND,"[6, 7]",blind_session,player_action,1.755221e+09,NaN,1755219722_3625_R9-26_1755221387

In [14]:
df = states.join(actions, on='context_id')
df.head()

ValueError: You are trying to merge on object and int64 columns for key 'context_id'. If you wish to proceed you should use pd.concat